namespace DDDFileReader.Lookups
{
    public class EventFaultPurposeLookupTable : LookupTable
    {
        public EventFaultPurposeLookupTable()
        {
            Add("00", "One of the 10 most recent (or last) events or faults");
            Add("01", "The longest event for one of the last 10 days of occurrence");
            Add("02", "One of the 5 longest events over the last 365 days");
            Add("03", "The last event for one of the last 10 days of occurrence");
            Add("04", "The most serious event for one of the last 10 days of occurrence");
            Add("05", "One of the 5 most serious events over the last 365 days");
            Add("06", "The first event or fault having occurred after the last calibration");
            Add("07", "An active/on-going event or fault");
            Add("08", "Reserved for future use");
            Add("09", "Reserved for future use");
            Add("0A", "Reserved for future use");
            Add("0B", "Reserved for future use");
            Add("0C", "Reserved for future use");
            Add("0D", "Reserved for future use");
            Add("0E", "Reserved for future use");
            Add("0F", "Reserved for future use");
            Add("10", "Reserved for future use");
            Add("11", "Reserved for future use");
            Add("12", "Reserved for future use");
            Add("13", "Reserved for future use");
            Add("14", "Reserved for future use");
            Add("15", "Reserved for future use");
            Add("16", "Reserved for future use");
            Add("17", "Reserved for future use");
            Add("18", "Reserved for future use");
            Add("19", "Reserved for future use");
            Add("1A", "Reserved for future use");
            Add("1B", "Reserved for future use");
            Add("1C", "Reserved for future use");
            Add("1D", "Reserved for future use");
            Add("1E", "Reserved for future use");
            Add("1F", "Reserved for future use");
            Add("20", "Reserved for future use");
            Add("21", "Reserved for future use");
            Add("22", "Reserved for future use");
            Add("23", "Reserved for future use");
            Add("24", "Reserved for future use");
            Add("25", "Reserved for future use");
            Add("26", "Reserved for future use");
            Add("27", "Reserved for future use");
            Add("28", "Reserved for future use");
            Add("29", "Reserved for future use");
            Add("2A", "Reserved for future use");
            Add("2B", "Reserved for future use");
            Add("2C", "Reserved for future use");
            Add("2D", "Reserved for future use");
            Add("2E", "Reserved for future use");
            Add("2F", "Reserved for future use");
            Add("30", "Reserved for future use");
            Add("31", "Reserved for future use");
            Add("32", "Reserved for future use");
            Add("33", "Reserved for future use");
            Add("34", "Reserved for future use");
            Add("35", "Reserved for future use");
            Add("36", "Reserved for future use");
            Add("37", "Reserved for future use");
            Add("38", "Reserved for future use");
            Add("39", "Reserved for future use");
            Add("3A", "Reserved for future use");
            Add("3B", "Reserved for future use");
            Add("3C", "Reserved for future use");
            Add("3D", "Reserved for future use");
            Add("3E", "Reserved for future use");
            Add("3F", "Reserved for future use");
            Add("40", "Reserved for future use");
            Add("41", "Reserved for future use");
            Add("42", "Reserved for future use");
            Add("43", "Reserved for future use");
            Add("44", "Reserved for future use");
            Add("45", "Reserved for future use");
            Add("46", "Reserved for future use");
            Add("47", "Reserved for future use");
            Add("48", "Reserved for future use");
            Add("49", "Reserved for future use");
            Add("4A", "Reserved for future use");
            Add("4B", "Reserved for future use");
            Add("4C", "Reserved for future use");
            Add("4D", "Reserved for future use");
            Add("4E", "Reserved for future use");
            Add("4F", "Reserved for future use");
            Add("50", "Reserved for future use");
            Add("51", "Reserved for future use");
            Add("52", "Reserved for future use");
            Add("53", "Reserved for future use");
            Add("54", "Reserved for future use");
            Add("55", "Reserved for future use");
            Add("56", "Reserved for future use");
            Add("57", "Reserved for future use");
            Add("58", "Reserved for future use");
            Add("59", "Reserved for future use");
            Add("5A", "Reserved for future use");
            Add("5B", "Reserved for future use");
            Add("5C", "Reserved for future use");
            Add("5D", "Reserved for future use");
            Add("5E", "Reserved for future use");
            Add("5F", "Reserved for future use");
            Add("60", "Reserved for future use");
            Add("61", "Reserved for future use");
            Add("62", "Reserved for future use");
            Add("63", "Reserved for future use");
            Add("64", "Reserved for future use");
            Add("65", "Reserved for future use");
            Add("66", "Reserved for future use");
            Add("67", "Reserved for future use");
            Add("68", "Reserved for future use");
            Add("69", "Reserved for future use");
            Add("6A", "Reserved for future use");
            Add("6B", "Reserved for future use");
            Add("6C", "Reserved for future use");
            Add("6D", "Reserved for future use");
            Add("6E", "Reserved for future use");
            Add("6F", "Reserved for future use");
            Add("70", "Reserved for future use");
            Add("71", "Reserved for future use");
            Add("72", "Reserved for future use");
            Add("73", "Reserved for future use");
            Add("74", "Reserved for future use");
            Add("75", "Reserved for future use");
            Add("76", "Reserved for future use");
            Add("77", "Reserved for future use");
            Add("78", "Reserved for future use");
            Add("79", "Reserved for future use");
            Add("7A", "Reserved for future use");
            Add("7B", "Reserved for future use");
            Add("7C", "Reserved for future use");
            Add("7D", "Reserved for future use");
            Add("7E", "Reserved for future use");
            Add("7F", "Reserved for future use");
            Add("80", "Manufacturer specific");
            Add("81", "Manufacturer specific");
            Add("82", "Manufacturer specific");
            Add("83", "Manufacturer specific");
            Add("84", "Manufacturer specific");
            Add("85", "Manufacturer specific");
            Add("86", "Manufacturer specific");
            Add("87", "Manufacturer specific");
            Add("88", "Manufacturer specific");
            Add("89", "Manufacturer specific");
            Add("8A", "Manufacturer specific");
            Add("8B", "Manufacturer specific");
            Add("8C", "Manufacturer specific");
            Add("8D", "Manufacturer specific");
            Add("8E", "Manufacturer specific");
            Add("8F", "Manufacturer specific");
            Add("90", "Manufacturer specific");
            Add("91", "Manufacturer specific");
            Add("92", "Manufacturer specific");
            Add("93", "Manufacturer specific");
            Add("94", "Manufacturer specific");
            Add("95", "Manufacturer specific");
            Add("96", "Manufacturer specific");
            Add("97", "Manufacturer specific");
            Add("98", "Manufacturer specific");
            Add("99", "Manufacturer specific");
            Add("9A", "Manufacturer specific");
            Add("9B", "Manufacturer specific");
            Add("9C", "Manufacturer specific");
            Add("9D", "Manufacturer specific");
            Add("9E", "Manufacturer specific");
            Add("9F", "Manufacturer specific");
            Add("A0", "Manufacturer specific");
            Add("A1", "Manufacturer specific");
            Add("A2", "Manufacturer specific");
            Add("A3", "Manufacturer specific");
            Add("A4", "Manufacturer specific");
            Add("A5", "Manufacturer specific");
            Add("A6", "Manufacturer specific");
            Add("A7", "Manufacturer specific");
            Add("A8", "Manufacturer specific");
            Add("A9", "Manufacturer specific");
            Add("AA", "Manufacturer specific");
            Add("AB", "Manufacturer specific");
            Add("AC", "Manufacturer specific");
            Add("AD", "Manufacturer specific");
            Add("AE", "Manufacturer specific");
            Add("AF", "Manufacturer specific");
            Add("B0", "Manufacturer specific");
            Add("B1", "Manufacturer specific");
            Add("B2", "Manufacturer specific");
            Add("B3", "Manufacturer specific");
            Add("B4", "Manufacturer specific");
            Add("B5", "Manufacturer specific");
            Add("B6", "Manufacturer specific");
            Add("B7", "Manufacturer specific");
            Add("B8", "Manufacturer specific");
            Add("B9", "Manufacturer specific");
            Add("BA", "Manufacturer specific");
            Add("BB", "Manufacturer specific");
            Add("BC", "Manufacturer specific");
            Add("BD", "Manufacturer specific");
            Add("BE", "Manufacturer specific");
            Add("BF", "Manufacturer specific");
            Add("C0", "Manufacturer specific");
            Add("C1", "Manufacturer specific");
            Add("C2", "Manufacturer specific");
            Add("C3", "Manufacturer specific");
            Add("C4", "Manufacturer specific");
            Add("C5", "Manufacturer specific");
            Add("C6", "Manufacturer specific");
            Add("C7", "Manufacturer specific");
            Add("C8", "Manufacturer specific");
            Add("C9", "Manufacturer specific");
            Add("CA", "Manufacturer specific");
            Add("CB", "Manufacturer specific");
            Add("CC", "Manufacturer specific");
            Add("CD", "Manufacturer specific");
            Add("CE", "Manufacturer specific");
            Add("CF", "Manufacturer specific");
            Add("D0", "Manufacturer specific");
            Add("D1", "Manufacturer specific");
            Add("D2", "Manufacturer specific");
            Add("D3", "Manufacturer specific");
            Add("D4", "Manufacturer specific");
            Add("D5", "Manufacturer specific");
            Add("D6", "Manufacturer specific");
            Add("D7", "Manufacturer specific");
            Add("D8", "Manufacturer specific");
            Add("D9", "Manufacturer specific");
            Add("DA", "Manufacturer specific");
            Add("DB", "Manufacturer specific");
            Add("DC", "Manufacturer specific");
            Add("DD", "Manufacturer specific");
            Add("DE", "Manufacturer specific");
            Add("DF", "Manufacturer specific");
            Add("E0", "Manufacturer specific");
            Add("E1", "Manufacturer specific");
            Add("E2", "Manufacturer specific");
            Add("E3", "Manufacturer specific");
            Add("E4", "Manufacturer specific");
            Add("E5", "Manufacturer specific");
            Add("E6", "Manufacturer specific");
            Add("E7", "Manufacturer specific");
            Add("E8", "Manufacturer specific");
            Add("E9", "Manufacturer specific");
            Add("EA", "Manufacturer specific");
            Add("EB", "Manufacturer specific");
            Add("EC", "Manufacturer specific");
            Add("ED", "Manufacturer specific");
            Add("EE", "Manufacturer specific");
            Add("EF", "Manufacturer specific");
            Add("F0", "Manufacturer specific");
            Add("F1", "Manufacturer specific");
            Add("F2", "Manufacturer specific");
            Add("F3", "Manufacturer specific");
            Add("F4", "Manufacturer specific");
            Add("F5", "Manufacturer specific");
            Add("F6", "Manufacturer specific");
            Add("F7", "Manufacturer specific");
            Add("F8", "Manufacturer specific");
            Add("F9", "Manufacturer specific");
            Add("FA", "Manufacturer specific");
            Add("FB", "Manufacturer specific");
            Add("FC", "Manufacturer specific");
            Add("FD", "Manufacturer specific");
            Add("FE", "Manufacturer specific");
            Add("FF", "Manufacturer specific");
        }
    }
}